version: "3"

services:
  app1:
    image: 'tag:latest'
    ports:
      - '8080'
    environment:
      NETOLOGY_PROFILE_DEV: 'true'
  app2:
    image: 'tag:latest'
    ports:
      - '8080'
    environment:
      NETOLOGY_PROFILE_DEV: 'false'
    depends_on:
      - app1